"""Reusable, local-first components for CIAL Knowledge OS."""

from .batch_qa import (
    CSV_COLUMNS,
    PHASE2_CSV_COLUMNS,
    PHASE3_CSV_COLUMNS,
    BatchAnswerCollection,
    collect_batch_answers,
    export_batch_answers,
)
from .benchmarking import Timer, benchmark_pipeline_steps, print_benchmark_table
from .benchmark_loader import Benchmark, BenchmarkQuestion, load_benchmark
from .chunking import chunk_documents, summarize_chunks
from .citations import (
    build_citations,
    render_answer_with_citations,
    render_citations,
)
from .citation_links import CitationLinkBuilder
from .config import KnowledgeOSConfig, Phase2Config, Phase3Config, RunArtifactNames
from .context_builder import (
    INSUFFICIENT_EVIDENCE_RESPONSE,
    ContextBuilder,
    ContextBuildResult,
    compress_context,
    merge_overlapping_chunks,
)
from .embeddings import embed_texts, get_embedding_dimension, load_embedding_model
from .evaluation_metrics import (
    aggregate_experiment,
    evaluate_answer,
    rank_experiments,
)
from .evaluation_report import (
    build_recommendations,
    write_recommendation_report,
)
from .experiment_config import ExperimentConfig, ExperimentGrid
from .experiment_runner import (
    ExperimentRunner,
    ExperimentSweepResult,
    ReconfiguringPipelineFactory,
)
from .fusion import ReciprocalRankFusion
from .llm import build_grounded_prompt, create_local_llm, generate_answer
from .loaders import (
    create_sample_airport_documents,
    load_all_documents,
    load_pdf_documents,
    load_text_documents,
    summarize_documents,
)
from .rag_pipeline import BasicRAGPipeline
from .phase2_pipeline import Phase2RAGPipeline
from .phase3_pipeline import Phase3RAGPipeline
from .phase3_reporting import (
    write_results_csv,
    write_results_xlsx,
    write_latency_svg,
    write_standalone_html,
)
from .phase3_runner import Phase3Runner, Phase3RunResult
from .query_transformations import (
    QueryTransformer,
    QueryVariant,
    expand_query_keywords,
    reformulate_for_domain,
    rewrite_query,
)
from .retrieval import (
    format_retrieved_context,
    print_retrieval_results,
    search_similar_chunks,
)
from .retrieval_postprocessing import (
    deduplicate_results,
    expand_neighbor_chunks,
    retrieve_multiple_queries,
)
from .retrievers import (
    BM25Retriever,
    DenseRetriever,
    HybridRetriever,
    Retriever,
    default_bm25_tokenize,
)
from .run_manager import RunManager, RunPaths
from .token_budget import (
    DEFAULT_TIKTOKEN_ENCODING,
    TiktokenTokenizer,
    TokenBudgetManager,
    TokenBudgetUsage,
    TokenManager,
    create_token_budget_manager,
    create_token_manager,
)
from .vectorstore import (
    create_qdrant_client,
    ensure_collection,
    index_chunks,
    recreate_collection,
    reset_qdrant_storage,
)
from .visualization import (
    batch_retrieval_trace_table,
    citation_quality_table,
    context_stage_counts_table,
    display_context_sections_table,
    display_high_duplicate_chunks_table,
    display_low_score_chunks_table,
    display_query_variant_contribution_table,
    display_retrieval_trace_table,
    display_top_sources_table,
    duplicate_chunk_frequency_table,
    neighbor_expansion_table,
    plot_answer_status_distribution,
    plot_chunk_size_distribution,
    plot_context_compression_ratio,
    plot_context_section_lengths,
    plot_context_stage_counts,
    plot_duplicate_chunk_frequency,
    plot_latency_by_question,
    plot_page_distribution,
    plot_query_variant_contribution,
    plot_retrieval_comparison,
    plot_retrieval_funnel,
    plot_retrieval_scores,
    plot_score_by_query_variant,
    plot_score_distribution,
    plot_source_distribution,
    plot_timing_breakdown,
    query_variants_table,
    retrieval_chunks_table,
    retrieval_comparison_table,
)
from .visualization_dashboard import generate_dashboard, load_dashboard_data

__all__ = [
    "BasicRAGPipeline",
    "Benchmark",
    "BenchmarkQuestion",
    "CSV_COLUMNS",
    "PHASE2_CSV_COLUMNS",
    "PHASE3_CSV_COLUMNS",
    "BatchAnswerCollection",
    "BM25Retriever",
    "CitationLinkBuilder",
    "DenseRetriever",
    "DEFAULT_TIKTOKEN_ENCODING",
    "HybridRetriever",
    "KnowledgeOSConfig",
    "Phase2Config",
    "Phase3Config",
    "Phase2RAGPipeline",
    "Phase3RAGPipeline",
    "Phase3Runner",
    "Phase3RunResult",
    "ReciprocalRankFusion",
    "Retriever",
    "RunArtifactNames",
    "RunManager",
    "RunPaths",
    "TokenBudgetManager",
    "TokenBudgetUsage",
    "TokenManager",
    "TiktokenTokenizer",
    "ContextBuilder",
    "ContextBuildResult",
    "ExperimentConfig",
    "ExperimentGrid",
    "ExperimentRunner",
    "ExperimentSweepResult",
    "INSUFFICIENT_EVIDENCE_RESPONSE",
    "QueryTransformer",
    "QueryVariant",
    "ReconfiguringPipelineFactory",
    "Timer",
    "benchmark_pipeline_steps",
    "batch_retrieval_trace_table",
    "aggregate_experiment",
    "build_grounded_prompt",
    "build_citations",
    "build_recommendations",
    "chunk_documents",
    "collect_batch_answers",
    "citation_quality_table",
    "create_local_llm",
    "create_qdrant_client",
    "create_sample_airport_documents",
    "create_token_budget_manager",
    "create_token_manager",
    "compress_context",
    "context_stage_counts_table",
    "deduplicate_results",
    "default_bm25_tokenize",
    "display_context_sections_table",
    "display_high_duplicate_chunks_table",
    "display_low_score_chunks_table",
    "display_query_variant_contribution_table",
    "display_retrieval_trace_table",
    "display_top_sources_table",
    "duplicate_chunk_frequency_table",
    "embed_texts",
    "ensure_collection",
    "expand_neighbor_chunks",
    "expand_query_keywords",
    "export_batch_answers",
    "evaluate_answer",
    "format_retrieved_context",
    "generate_answer",
    "generate_dashboard",
    "get_embedding_dimension",
    "index_chunks",
    "load_all_documents",
    "load_benchmark",
    "load_dashboard_data",
    "load_embedding_model",
    "load_pdf_documents",
    "load_text_documents",
    "merge_overlapping_chunks",
    "neighbor_expansion_table",
    "plot_chunk_size_distribution",
    "plot_answer_status_distribution",
    "plot_context_compression_ratio",
    "plot_context_section_lengths",
    "plot_context_stage_counts",
    "plot_duplicate_chunk_frequency",
    "plot_latency_by_question",
    "plot_page_distribution",
    "plot_query_variant_contribution",
    "plot_retrieval_comparison",
    "plot_retrieval_funnel",
    "plot_retrieval_scores",
    "plot_score_by_query_variant",
    "plot_score_distribution",
    "plot_source_distribution",
    "plot_timing_breakdown",
    "print_benchmark_table",
    "print_retrieval_results",
    "query_variants_table",
    "rank_experiments",
    "recreate_collection",
    "reformulate_for_domain",
    "render_answer_with_citations",
    "render_citations",
    "reset_qdrant_storage",
    "retrieve_multiple_queries",
    "retrieval_chunks_table",
    "retrieval_comparison_table",
    "rewrite_query",
    "search_similar_chunks",
    "summarize_chunks",
    "summarize_documents",
    "write_recommendation_report",
    "write_results_csv",
    "write_results_xlsx",
    "write_latency_svg",
    "write_standalone_html",
]
